name: Create new branch and add text

on:
  push:
    branches:
      # Push events on main branch
      - main
      - master
      # Push events to branches matching refs/heads/releases/10
      - "releases/**"
      # Sequence of patterns matched against refs/tags
    tags:
      - v1 # Push events to v1 tag
      - v1.* # Push events to v1.0, v1.1, and v1.9 tags
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  create-new-branch:
    name: Create new branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout to this branch
        uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      # check for the branch
      - name: List branches
        shell: bash
        run: |
          echo "Hello Evan Sum ~ Swag money"
          git fetch
          git branch -a
      #     git fetch
      #     echo "============================================"
      #     echo "list both remote-tracking and local branches"
      #     git branch -a
      #     echo "============================================"
      #     echo "list remote-tracking branches"
      #     git branch -r
      #     echo "============================================"
      # - name: create branch if necessary
      # if: #if evanlovescodio is NOT in list of branches #${{ !github.event.issue.pull_request }}
      # uses: peterjgrainger/action-create-branch@v2.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: 'evanlovescodio'
      # env:
      #   MY_NAME: Evan Sum
      # run: |
      #   echo $MY_NAME
      #   curl "https://www.google.com/"
      #   #cmd line code to append lines to code.
      # new comment
