name: Create new branch and add text

on:
  push:
    branches:
      # Push events on main branch
      - main
      - master
      # Push events to branches matching refs/heads/releases/10
      - "releases/**"
      # Sequence of patterns matched against refs/tags
    tags:
      - v1 # Push events to v1 tag
      - v1.* # Push events to v1.0, v1.1, and v1.9 tags
  release:
    types:
      - created

jobs:
  create-new-branch:
    name: Create new branch
    # with:
    #   token: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout to this branch
        uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: echo secrest
        run: |
          echo This is a test
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{ github.actor }}
          echo ${{ github.email }}

      # check for the branch
      - name: List branches
        shell: bash
        env:
          VAR1: ${{ github.actor }}
        run: |
          ./.github/workflows/test.sh

          # git config --global user.email "actions@github.com"
          # git config --global user.name "GitHub Actions"
          git add -A

          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "why hello there" --author="$VAR1 <$VAR1@users.noreply.github.com>"

          # git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull origin --ff-only

          git push -u "HEAD:evanlovescodio"
      # https://github.community/t/how-does-one-commit-from-an-action/16127/3
      #     git fetch
      #     echo "============================================"
      #     echo "list both remote-tracking and local branches"
      #     git branch -a
      #     echo "============================================"
      #     echo "list remote-tracking branches"
      #     git branch -r
      #     echo "============================================"
      # - name: create branch if necessary
      # if: #if evanlovescodio is NOT in list of branches #${{ !github.event.issue.pull_request }}
      # uses: peterjgrainger/action-create-branch@v2.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: 'evanlovescodio'
      # env:
      #   MY_NAME: Evan Sum
      # run: |
      #   echo $MY_NAME
      #   curl "https://www.google.com/"
      #   #cmd line code to append lines to code.
      # new comment
